spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
# wchodzicie pod strone i nie musicie miec postmana zeby testowac: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html