spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
#tu wklei? identyfikator klienta
spring.security.oauth2.client.registration.google.client-id=
#tu wkleic tajny klucz klienta
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email
# wchodzicie pod strone i nie musicie miec postmana zeby testowac: http://localhost:8080/swagger-ui.html
springdoc.swQagger-ui.path=/swagger-ui.html