CREATE TABLE uzytkownicy (
                             id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             email           VARCHAR2(255) NOT NULL,
                             haslo_hash      VARCHAR2(255) NOT NULL,
                             imie            VARCHAR2(100) NOT NULL,
                             nazwisko        VARCHAR2(100) NOT NULL,
                             telefon         VARCHAR2(30),
                             rola            VARCHAR2(20) DEFAULT 'USER' NOT NULL,
                             utworzono       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                             CONSTRAINT pk_uzytkownicy PRIMARY KEY (id),
                             CONSTRAINT uq_uzytkownicy_email UNIQUE (email),
                             CONSTRAINT ck_uzytkownicy_rola CHECK (rola IN ('USER', 'ADMIN'))
);

CREATE TABLE lokalizacje (
                             id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                             kraj            VARCHAR2(100) NOT NULL,
                             miasto          VARCHAR2(100) NOT NULL,
                             ulica           VARCHAR2(150),
                             nr_budynku      VARCHAR2(20),
                             kod_pocztowy    VARCHAR2(20),

                             CONSTRAINT pk_lokalizacje PRIMARY KEY (id)
);

CREATE TABLE hotele (
                        id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        lokalizacja_id  NUMBER NOT NULL,
                        nazwa           VARCHAR2(200) NOT NULL,
                        opis            VARCHAR2(4000 CHAR),
                        gwiazdki        NUMBER(1) DEFAULT 3,
                        telefon         VARCHAR2(30),
                        email           VARCHAR2(255),

                        CONSTRAINT pk_hotele PRIMARY KEY (id),
                        CONSTRAINT fk_hotele_lokalizacja
                            FOREIGN KEY (lokalizacja_id) REFERENCES lokalizacje(id),
                        CONSTRAINT ck_hotele_gwiazdki CHECK (gwiazdki BETWEEN 1 AND 5)
);

CREATE TABLE pokoje (
                        id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        hotel_id        NUMBER NOT NULL, -- Zmienione z lokalizacja_id
                        numer_pokoju    VARCHAR2(30),
                        nazwa           VARCHAR2(150) NOT NULL,
                        opis            VARCHAR2(4000 CHAR),
                        liczba_lozek    NUMBER(2) NOT NULL,
                        max_osob        NUMBER(2) NOT NULL,
                        cena_bazowa     NUMBER(10,2) NOT NULL,
                        waluta          VARCHAR2(3) DEFAULT 'PLN' NOT NULL,
                        status          VARCHAR2(20) DEFAULT 'DOSTEPNY' NOT NULL,
                        utworzono       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                        CONSTRAINT pk_pokoje PRIMARY KEY (id),
                        CONSTRAINT fk_pokoje_hotele
                            FOREIGN KEY (hotel_id) REFERENCES hotele(id) ON DELETE CASCADE,
                        CONSTRAINT uq_pokoje_hotel_numer UNIQUE (hotel_id, numer_pokoju),
                        CONSTRAINT ck_pokoje_status CHECK (status IN ('DOSTEPNY', 'NIEDOSTEPNY', 'SERWIS'))
);


CREATE TABLE udogodnienia (
                              id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                              nazwa           VARCHAR2(100) NOT NULL,
                              kategoria       VARCHAR2(50),
                              opis            VARCHAR2(500),

                              CONSTRAINT pk_udogodnienia PRIMARY KEY (id),
                              CONSTRAINT uq_udogodnienia_nazwa UNIQUE (nazwa)
);

CREATE TABLE pokoj_udogodnienia (
                                    pokoj_id            NUMBER NOT NULL,
                                    udogodnienie_id     NUMBER NOT NULL,

                                    CONSTRAINT pk_pokoj_udogodnienia PRIMARY KEY (pokoj_id, udogodnienie_id),
                                    CONSTRAINT fk_pu_pokoj
                                        FOREIGN KEY (pokoj_id) REFERENCES pokoje(id) ON DELETE CASCADE,
                                    CONSTRAINT fk_pu_udogodnienie
                                        FOREIGN KEY (udogodnienie_id) REFERENCES udogodnienia(id) ON DELETE CASCADE
);

CREATE TABLE zdjecia_pokoi (
                               id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               pokoj_id            NUMBER NOT NULL,
                               url_zdjecia         VARCHAR2(1000) NOT NULL,
                               opis                VARCHAR2(500),
                               kolejnosc           NUMBER(4) DEFAULT 1 NOT NULL,
                               czy_glowne          NUMBER(1) DEFAULT 0 NOT NULL,

                               CONSTRAINT pk_zdjecia_pokoi PRIMARY KEY (id),
                               CONSTRAINT fk_zdjecia_pokoi_pokoj
                                   FOREIGN KEY (pokoj_id) REFERENCES pokoje(id) ON DELETE CASCADE,
                               CONSTRAINT ck_zdjecia_pokoi_kolejnosc CHECK (kolejnosc > 0),
                               CONSTRAINT ck_zdjecia_pokoi_czy_glowne CHECK (czy_glowne IN (0, 1))
);

CREATE TABLE rezerwacje (
                            id                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            uzytkownik_id           NUMBER NOT NULL,
                            pokoj_id                NUMBER NOT NULL,
                            data_zameldowania       DATE NOT NULL,
                            data_wymeldowania       DATE NOT NULL,
                            liczba_doroslych        NUMBER(2) DEFAULT 1 NOT NULL,
                            liczba_dzieci           NUMBER(2) DEFAULT 0 NOT NULL,
                            status                  VARCHAR2(20) DEFAULT 'OCZEKUJACA' NOT NULL,
                            kwota_calkowita         NUMBER(10,2) NOT NULL,
                            uwagi                   VARCHAR2(4000 CHAR),
                            utworzono               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                            anulowano_at            TIMESTAMP,

                            CONSTRAINT pk_rezerwacje PRIMARY KEY (id),
                            CONSTRAINT fk_rezerwacje_uzytkownik
                                FOREIGN KEY (uzytkownik_id) REFERENCES uzytkownicy(id),
                            CONSTRAINT fk_rezerwacje_pokoj
                                FOREIGN KEY (pokoj_id) REFERENCES pokoje(id),
                            CONSTRAINT ck_rezerwacje_daty CHECK (data_wymeldowania > data_zameldowania),
                            CONSTRAINT ck_rezerwacje_dorosli CHECK (liczba_doroslych >= 1),
                            CONSTRAINT ck_rezerwacje_dzieci CHECK (liczba_dzieci >= 0),
                            CONSTRAINT ck_rezerwacje_kwota CHECK (kwota_calkowita >= 0),
                            CONSTRAINT ck_rezerwacje_status CHECK (
                                status IN ('OCZEKUJACA', 'POTWIERDZONA', 'ANULOWANA', 'ZAKONCZONA')
                                )
);

CREATE TABLE platnosci (
                           id                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           rezerwacja_id           NUMBER NOT NULL,
                           kwota                   NUMBER(10,2) NOT NULL,
                           waluta                  VARCHAR2(3) DEFAULT 'PLN' NOT NULL,
                           metoda                  VARCHAR2(30) NOT NULL,
                           status                  VARCHAR2(20) DEFAULT 'OCZEKUJACA' NOT NULL,
                           numer_transakcji        VARCHAR2(100),
                           utworzono               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                           oplacono_at             TIMESTAMP,

                           CONSTRAINT pk_platnosci PRIMARY KEY (id),
                           CONSTRAINT fk_platnosci_rezerwacja
                               FOREIGN KEY (rezerwacja_id) REFERENCES rezerwacje(id),
                           CONSTRAINT uq_platnosci_numer_transakcji UNIQUE (numer_transakcji),
                           CONSTRAINT ck_platnosci_kwota CHECK (kwota >= 0),
                           CONSTRAINT ck_platnosci_status CHECK (
                               status IN ('OCZEKUJACA', 'OPLACONA', 'NIEUDANA', 'ZWROCONA')
                               )
);

CREATE TABLE opinie (
                        id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        rezerwacja_id       NUMBER NOT NULL,
                        uzytkownik_id       NUMBER NOT NULL,
                        pokoj_id            NUMBER NOT NULL,
                        ocena               NUMBER(10,0) NOT NULL,
                        komentarz           VARCHAR2(4000 CHAR),
                        utworzono           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                        CONSTRAINT pk_opinie PRIMARY KEY (id),
                        CONSTRAINT uq_opinie_rezerwacja UNIQUE (rezerwacja_id),
                        CONSTRAINT fk_opinie_rezerwacja
                            FOREIGN KEY (rezerwacja_id) REFERENCES rezerwacje(id),
                        CONSTRAINT fk_opinie_uzytkownik
                            FOREIGN KEY (uzytkownik_id) REFERENCES uzytkownicy(id),
                        CONSTRAINT fk_opinie_pokoj
                            FOREIGN KEY (pokoj_id) REFERENCES pokoje(id),
                        CONSTRAINT ck_opinie_ocena CHECK (ocena BETWEEN 1 AND 5)
);

CREATE TABLE powiadomienia (
                               id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               uzytkownik_id       NUMBER NOT NULL,
                               rezerwacja_id       NUMBER,
                               typ                 VARCHAR2(50) NOT NULL,
                               tresc               VARCHAR2(4000 CHAR) NOT NULL,
                               status              VARCHAR2(20) DEFAULT 'OCZEKUJE' NOT NULL,
                               utworzono           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                               wyslano_at          TIMESTAMP,

                               CONSTRAINT pk_powiadomienia PRIMARY KEY (id),
                               CONSTRAINT fk_powiadomienia_uzytkownik
                                   FOREIGN KEY (uzytkownik_id) REFERENCES uzytkownicy(id),
                               CONSTRAINT fk_powiadomienia_rezerwacja
                                   FOREIGN KEY (rezerwacja_id) REFERENCES rezerwacje(id),
                               CONSTRAINT ck_powiadomienia_status CHECK (
                                   status IN ('OCZEKUJE', 'WYSLANE', 'BLAD')
                                   )
);

CREATE TABLE ceny_pokoi (
                            id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            pokoj_id            NUMBER NOT NULL,
                            data_od             DATE NOT NULL,
                            data_do             DATE NOT NULL,
                            cena_za_noc         NUMBER(10,2) NOT NULL,
                            utworzono           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                            CONSTRAINT pk_ceny_pokoi PRIMARY KEY (id),
                            CONSTRAINT fk_ceny_pokoi_pokoj
                                FOREIGN KEY (pokoj_id) REFERENCES pokoje(id) ON DELETE CASCADE,
                            CONSTRAINT ck_ceny_pokoi_daty CHECK (data_do >= data_od),
                            CONSTRAINT ck_ceny_pokoi_cena CHECK (cena_za_noc >= 0)